### ISSUE TITLE
Sharing specifications: Unable to resolve smithy traits

### ISSUE THREAD

**Issue by anderha** [disneystreaming/smithy4s#420] opened 2022-08-31 11:50 UTC
Hi,

I am currently facing a problem sharing smithy files in sbt projects. 

I define the api of project A in smithy files and would like to reuse them in another project B to generate client code. 

To publish the smithy files I followed the docs on [sharing specifications](https://disneystreaming.github.io/smithy4s/docs/overview/sharing-specs/). Unfortunately the compile step in project B fails with an error: `Unable to resolve trait 'smithy4s.api#simpleRestJson'. If this is a custom trait, then it must be defined before it can be used in a model.`

The smithy files are defined as follows:
```
namespace com.example.api.definition
use smithy4s.api#simpleRestJson

@simpleRestJson
service PingAPIController {
    version: "1.0.0",
    operations: [ping]
}

@http(method: "GET", uri: "/", code: 200)
@readonly
operation ping {}
```

Compiling the smithy files in project A works like a charm. In project B I have other local smithy files for which the codegen does also work.

Technical details
- Smithy4sCodegenPlugin version: 0.14.2
- Scala version: 2.13.8

Am I missing something?

**Comment by Baccata** [comment] 2022-08-31 12:50
@anderha, closing because this is a duplicate of https://github.com/disneystreaming/smithy4s/issues/391

**Comment by Baccata** [comment] 2022-08-31 16:23
@anderha actually I'm not 100% sure it's a duplicate. Would you mind providing a minimal reproduction in the form of a github repository we could have a look at ?

**Comment by anderha** [comment] 2022-09-01 08:29
Hey @Baccata I have created a sample project: https://github.com/anderha/smithy-package-sample

I have placed a manual into the README.md to replicate the error

Steps to make it work:
- remove the `@simpleRestJson` in https://github.com/anderha/smithy-package-sample/blob/main/modules/api-definition/src/main/resources/META-INF/smithy/healthAPIController.smithy#L5 
- publish another version with `sbt publishLocal` in `modules/api-definition`
  - increase version number in https://github.com/anderha/smithy-package-sample/blob/main/modules/api-definition/build.sbt#L1
  - reference increased version number in https://github.com/anderha/smithy-package-sample/blob/main/build.sbt#L12
 - `sbt compile` in root
 
It might be a duplicate, but I am not sure also

**Comment by Baccata** [comment] 2022-09-01 08:40
Right yeah it's a partial overlap with the other issue. Head over [there](https://disneystreaming.github.io/smithy4s/docs/overview/sharing-specs#packaging-specifications-in-order-to-share-them) to see understand what's missing. 

We're gonna work to facilitate this usecase in a future version, that we'll hopefully release sometime in the next couple months.

**Comment by Baccata** [comment] 2022-09-17 08:56
Hey @anderha, 

so, I've given your issue a further look, and turns out I had mis-interpreted the problem, apologies. 

To give you an explanation, it basically has to do with smithy4s validating the smithy model resulting from loading what's in dependencies before merging them with local models. It essentially means that upstream models should be valid on their 
own. 

So essentially, all you need to do is adding the following line : 

``` 
    libraryDependencies += "com.disneystreaming.smithy4s" % "smithy4s-protocol" % "0.14.2"
```

in these settings [there](https://github.com/anderha/smithy-package-sample/blob/main/modules/api-definition/build.sbt#L4) , which means that the transitive set of dependencies of this api artifact contains a valid smithy model. 

Once agian, again, sorry for the mis-interpretation.

**Comment by Baccata** [comment] 2022-09-17 09:19
I'm adding a fix for this so that it will work without any dependency addition : https://github.com/disneystreaming/smithy4s/pull/462

**Closed** 2022-09-27 21:13 UTC
Labels: duplicate
