### ISSUE TITLE
Required defaults aren't written

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1289] opened 2023-11-06 21:38 UTC
According to [Smithy documentation](https://smithy.io/2.0/spec/type-refinement-traits.html?highlight=default#default-value-serialization):

> 2. All effective default values SHOULD be serialized. This ensures that messages are unambiguous and do not change during deserialization if the default value for a member changes after the message was serialized.

> 4. A member marked `@required` MUST be serialized, including members that have a default.

As far as I understand, this means that the following code (edited):

```scala
//> using lib "com.disneystreaming.smithy4s::smithy4s-json:0.18.3"
import smithy4s.json.JsoniterCodecCompiler

import smithy4s.json.Json
import smithy4s.Schema
import smithy4s.Document
import smithy.api.Default

case class C(s: String, i: Option[Int])

object C {

  implicit val schema: Schema[C] =
    Schema.struct[C](
      Schema
        .string
        .required[C]("s", _.s)
        .addHints(Default(Document.fromString("hello"))),
      Schema.int.optional[C]("i", _.i).addHints(Default(Document.fromInt(42))),
    )(C.apply)

}

def write[A: Schema](a: A) = Json.writeBlob(a).toUTF8String

write(C("hello", Some(42)))
// res0: String = {}
write(C("hello2", None))
// res1: String = {"s":"hello2","i":null}

```

should/must write this:

`C("hello", None)` -> `{"s": "hello", "i": 42}`

whereas it serializes as:

`{"i": null}`.

- `s` is a required member so MUST be serialized according to rule 4 from the docs
- `i`'s effective default SHOULD be serialized so that it's unambiguous on deserialization.

Looking forward to thoughts on how we should act: I think the encoders for JSON, HTTP metadata, XML and documents (and any others we may have) should be updated to account for these rules: basically write the default by default, only using another value if it's non-null.

**Comment by kubukoz** [comment] 2023-11-06 23:01
Some context, we have things currently being written without defaults, and the consumers of that data aren't all Smithy based (or don't support `@default` for reads) - so getting them to see these defaults would require a sizeable effort. It's too late to update the existing data, but having these defaults in the payloads would be significantly easier to manage.

I think this is mostly a problem for fields that are `required` - if you're a consumer who's using Smithy, you can't _just_ support the `@required` trait, you also must support `@default` if you're trying to parse smithy4s-written data. That said, it'd be best if required/optional were treated consistently, in my book.

**Comment by Baccata** [comment] 2023-11-07 13:42
Removing the bug label because this discussion is inherently protocol specific (despite AWS), and subject to interpretation without the context of a particular protocol. 

> A member marked `@required` MUST be serialized, including members that have a default. 

I can agree with this : generally speaking, I think it is fair to expect that a member marked as required should be part of a serialised payload. 

> All effective default values SHOULD be serialized.

I wholefully disagree with this, without the context of a protocol. The opportunity to skip the serialisation of some values is interesting for performance reason. Less thing on the wire is good. 

I do however agree that serialisers should provide some level of customisation. 

> whereas it serializes as: ...

Can you amend your snippet to showcase exactly the bit of logic that performs the serialisation ? Also, for the sake of the discussion, it's worth noting that your handcrafted schema doesn't reflect the reality that happens at code-generation time, where non-required fields that have a default 

#### What steps should be taken at this point in time ? 

* On the SimpleRestJson side : nothing at this time. The expected behaviour wrt default values has not been established for the protocol. This issue can be used as an opportunity to refine/define, but I will probably veto a blind following of what AWS says in their documentation. It's always been our policy to take their directives with a grain of salt and apply critical thinking. 
* On the SXM side : you should not use SimpleRestJson. This will give you the control over the semantics of the protocol for your organisation, and provide opportunities to diverge from defaults provided by smithy4s when we are not in agreement over protocol semantics.

**Comment by kubukoz** [comment] 2023-11-07 14:53
> Can you amend your snippet to showcase exactly the bit of logic that performs the serialisation ?

Apologies, it got trimmed out. I was just using `Json.writeBlob(_).toUTF8String`, which obviously uses the default config and doesn't write explicit defaults.

In a separate conversation, you've reminded me about `withExplicitDefaultsEncoding` - this seems to behave as desired:

```scala
//> using lib "com.disneystreaming.smithy4s::smithy4s-json:0.18.3"
import smithy4s.json.JsoniterCodecCompiler

import smithy4s.json.Json
import smithy4s.Schema
import smithy4s.Document
import smithy.api.Default

case class C(s: String, i: Option[Int])

object C {

  implicit val schema: Schema[C] =
    Schema.struct[C](
      Schema
        .string
        .required[C]("s", _.s)
        .addHints(Default(Document.fromString("hello"))),
      Schema.int.optional[C]("i", _.i).addHints(Default(Document.fromInt(42))),
    )(C.apply)

}

def write[A: Schema](a: A) = Json.writeBlob(a).toUTF8String

write(C("hello", Some(42)))
// res0: String = {}
write(C("hello2", None))
// res1: String = {"s":"hello2","i":null}

def write2[A: Schema](a: A) =
  Json
    .payloadCodecs
    .withJsoniterCodecCompiler(
      Json.jsoniter.withExplicitDefaultsEncoding(true)
    )
    .encoders
    .fromSchema(summon[Schema[A]])
    .encode(a)
    .toUTF8String

write2(C("hello", Some(42)))
// res2: String = {"s":"hello","i":42}
write2(C("hello2", None))
// res3: String = {"s":"hello2","i":null}
```

That's good enough for me 😅 

> for the sake of the discussion, it's worth noting that your handcrafted schema doesn't reflect the reality that happens at code-generation time, where non-required fields that have a default

seems like an incomplete sentence but I think I see your point. The generated code from

```smithy
$version: "2"

namespace demo

structure C {
    @required
    s: String = "hello"
    i: Integer = 42
}
```

looks like this

```scala
package demo

import smithy4s.Hints
import smithy4s.Schema
import smithy4s.ShapeId
import smithy4s.ShapeTag
import smithy4s.schema.Schema.int
import smithy4s.schema.Schema.string
import smithy4s.schema.Schema.struct

final case class C(s: String = "hello", i: Int = 42)

object C extends ShapeTag.Companion[C] {
  val id: ShapeId = ShapeId("demo", "C")

  val hints: Hints = Hints.empty

  implicit val schema: Schema[C] = struct(
    string.required[C]("s", _.s).addHints(smithy.api.Default(smithy4s.Document.fromString("hello"))),
    int.required[C]("i", _.i).addHints(smithy.api.Default(smithy4s.Document.fromDouble(42.0d))),
  ){
    C.apply
  }.withId(id).addHints(hints)
}
```

which means that `i` is no longer optional. That said, if you set it to `42` or use the default parameter, it works the same way as the required `s` field:

```scala

//> using lib "com.disneystreaming.smithy4s::smithy4s-json:0.18.3"
import smithy4s.json.JsoniterCodecCompiler

import smithy4s.json.Json
import smithy4s.Schema
import demo.C

def write[A: Schema](a: A) = Json.writeBlob(a).toUTF8String

write(C("hello", 42))
// res0: String = {}
write(C("hello2", 10))
// res1: String = {"s":"hello2","i":10}

def write2[A: Schema](a: A) =
  Json
    .payloadCodecs
    .withJsoniterCodecCompiler(
      Json.jsoniter.withExplicitDefaultsEncoding(true)
    )
    .encoders
    .fromSchema(summon[Schema[A]])
    .encode(a)
    .toUTF8String

write2(C("hello", 42))
// res2: String = {"s":"hello","i":42}
write2(C("hello2", 10))
// res3: String = {"s":"hello2","i":10}
```

Looks like I'm good on the JSON side then. I'll look into what other pieces would need to have similar configuration options, but for my current usecase it'd probably be just `Document.Encoder` and `Metadata.Encoder`.

**Comment by kubukoz** [comment] 2023-11-07 22:52
Spun off https://github.com/disneystreaming/smithy4s/issues/1290 to allow configuration of non-JSON cases.

**Comment by kubukoz** [comment] 2023-11-07 22:53
> > A member marked `@required` MUST be serialized, including members that have a default.
> 
> I can agree with this : generally speaking, I think it is fair to expect that a member marked as required should be part of a serialised payload.

do you think this should be true regardless of config?

**Comment by kubukoz** [comment] 2023-11-07 23:17
(only keeping open to not forget the last comment's issue)

**Closed as completed** 2023-11-22 10:09 UTC
