### ISSUE TITLE
Codegen not producing compilable code on latest EC2 spec

### ISSUE THREAD

**Issue by igor-ramazanov** [disneystreaming/smithy4s#674] opened 2022-12-13 14:23 UTC
Hi and thank you for your work.

I couldn't set [the basic example](https://disneystreaming.github.io/smithy4s/docs/protocols/aws/aws) from the docs [working](https://github.com/igor-ramazanov/scala-playground).

Copied the `dynamodb.json` into the `src/main/smithy/`, added the SBT plugin and it fails with:
```
sbt:scala-playground> compile
[error] stack trace is suppressed; run last Compile / smithy4sCodegen for the full output
[error] (Compile / smithy4sCodegen) software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events:
[error] [ERROR] com.amazonaws.dynamodb#DynamoDB_20120810: Unable to resolve trait `smithy.rules#endpointRuleSet`. If this is a custom trait, then it must be defined before it can be used in a model. | Model /home/igor/personal/scala-playground/src/main/smithy/dynamodb.json:3401:41
[error] [ERROR] com.amazonaws.dynamodb#DynamoDB_20120810: Unable to resolve trait `smithy.rules#endpointTests`. If this is a custom trait, then it must be defined before it can be used in a model. | Model /home/igor/personal/scala-playground/src/main/smithy/dynamodb.json:3765:39
[error] Total time: 1 s, completed Dec 13, 2022, 1:40:19 PM
```

Most probably, I'm missing something fundamental, will be happy to contribute to the docs!

**Comment by Baccata** [comment] 2022-12-13 14:58
Hey @igor-ramazanov , looks like AWS has added some dependencies to the models of their SDK. We don't control these models, obviously, so it may occur that sometimes our documentation would fall out of sync as we' don't build them upstream. 

Anyway :  I've managed to generate the dynamodb code by adding these settings : 

``` 
    Compile / smithy4sAllowedNamespaces := List(
      "smithy.rules",
      "com.amazonaws.dynamodb"
    ),
    libraryDependencies ++= Seq(
      "com.disneystreaming.smithy4s" %% "smithy4s-aws-http4s" % smithy4sVersion.value,
      "software.amazon.smithy" % "smithy-rules-engine" % smithy4s.codegen.BuildInfo.smithyVersion % Smithy4s
    )
```

**Comment by igor-ramazanov** [comment] 2022-12-13 16:01
It's a numbers narrowing, not widening, so there's no way to silent this with `-Wconf`.

**Comment by Baccata** [comment] 2022-12-13 16:03
Mmm interesting. So it fails at compile time ? Can you upload a reproduction repo, if that's not too much to ask ?

**Comment by igor-ramazanov** [comment] 2022-12-13 16:06
@Baccata Sure, I've updated [the repo](https://github.com/igor-ramazanov/scala-playground).

**Comment by Baccata** [comment] 2022-12-14 10:05
I should have a fix soon (there's more to it than just the numeric issue)

**Comment by Baccata** [comment] 2022-12-14 17:06
@igor-ramazanov this PR : https://github.com/disneystreaming/smithy4s/pull/677 should be sufficient for your code to compile. We've not performed a release yet (waiting on some other things), but you can run `publishLocal` of what you need in the library and try it out that way. 

**Unfortunately**, as I stated on [Discord](https://discord.com/channels/632150470000902164/635669047588945930/1052571464638922823), the fact that it compiles doesn't mean it'll work. Indeed, we haven't implemented the protocol [EC2 uses](https://smithy.io/2.0/aws/protocols/aws-ec2-query-protocol.html?highlight=ec2). The only protocol we've implemented so far (for AWS) is [AWS Json](https://smithy.io/2.0/aws/protocols/aws-json-1_0-protocol.html). You can see the list of the implemented protocols [there](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/aws-kernel/src/smithy4s/aws/AwsProtocol.scala#L41-L42) 

(as a matter of fact we'd appreciate a contribution to our documentation that would reflect that list). 

Depending on your needs and motivation, I'd be happy to offer guidance for implementing the protocol in question. Part of it has to do with XML, and we have [open-PRs](https://github.com/disneystreaming/smithy4s/pull/503) for that. The rest might be more straightforward, but with AWS, the Devil's very much in the details.

**Comment by Baccata** [comment] 2022-12-14 17:13
I'm closing this issue in favour of
* https://github.com/disneystreaming/smithy4s/issues/678
* https://github.com/disneystreaming/smithy4s/issues/679

**Closed by Baccata** 2022-12-14 17:13 UTC

**Comment by igor-ramazanov** [comment] 2022-12-15 09:16
@Baccata Thank you! Yeah, I see that now. I definitely would like to see and contribute the [AWS query](https://smithy.io/2.0/aws/protocols/aws-query-protocol.html) and [AWS EC2 query](https://smithy.io/2.0/aws/protocols/aws-ec2-query-protocol.html) to smithy4s, but it'll take quite a time for me to understand the codebase. Perhaps, a quick pairing session to skim over the codebase is too much to ask? :)

**Comment by Baccata** [comment] 2022-12-15 09:20
Sure, I'm AFK til Monday but we could do something next week ? Unless someone else is free before then

**Comment by igor-ramazanov** [comment] 2022-12-15 09:22
@Baccata Sounds good to me! Let's sync up in Discord, and have a great time!
