### ISSUE TITLE
[AWS] Add support for the awsQueryError trait

### ISSUE THREAD

**Issue by igor-ramazanov** [disneystreaming/smithy4s#732] opened 2023-01-16 13:22 UTC
Related to the https://github.com/disneystreaming/smithy4s/issues/720.

Target the https://github.com/disneystreaming/smithy4s/tree/feature/aws-query-protocol branch.

Add support for https://smithy.io/2.0/aws/protocols/aws-query-protocol.html#aws-protocols-awsqueryerror-trait trait according to the spec.

**Comment by igor-ramazanov** [comment] 2023-01-16 13:50
@Baccata I need a guidance to understand where to start from :raised_hands:

**Comment by Baccata** [comment] 2023-01-16 15:04
Right, so errors returned by AwsQuery servers look like this : 

https://smithy.io/2.0/aws/protocols/aws-query-protocol.html#operation-error-serialization

As you can see, the `Code` value serves as a discriminator, usually receives the name of the Shape, unless the `awsQueryError` trait is used, at which point the custom name should be in there. 

Now the problem is that this way of specifying the discriminator differs greatly from what happens in AWS-JSON protocols, where the discriminator goes in headers. The reason it's a problem is that right now the `AwsUnaryEndpoint` construct assumes that the discriminator is found in headers, before we even start consuming the body. See [here](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/aws/src/smithy4s/aws/internals/AwsUnaryEndpoint.scala#L72-L84). In comparison, here we need to parse the body as xml before we can discriminate between several errors. 

#### First : facilitating the identification of error schemas 

First we add a case object `Error` in the `InputOutput` [construct](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/core/src/smithy4s/internals/InputOutput.scala). This will break compatibility but it's an internal package so I'm fine with it. We then render that trait [here](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/codegen/src/smithy4s/codegen/internals/Renderer.scala#L580) like we do for input and output [there](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/codegen/src/smithy4s/codegen/internals/Renderer.scala#L383-L384) 

#### Second : 

We need to amend the Xml document decoder to support another way of encoding and decoding [unions](https://github.com/disneystreaming/smithy4s/blob/feature/aws-query-protocol/modules/xml/src/smithy4s/xml/internals/XmlDecoderSchemaVisitor.scala#L151-L178), that would be guided by our already existing `alloy#discriminated` trait. You can get inspiration from how that trait is handled in the [DocumentDecoder](https://github.com/disneystreaming/smithy4s/blob/feature/aws-query-protocol/modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala#L455-L459), and understand what it conceptually does by reading our [documentation](https://disneystreaming.github.io/smithy4s/docs/codegen/unions#discriminated-union). 

This `discriminated` trait is not something that is defined or supported by AWS, but in this context it's basically what we need, and we use it as a middleman to keep the Xml Schema Visitors decoupled from AWS (which they don't have awareness of). Instead of `JsonName`, `XmlName` should be used. 

#### Third 

Add an `xmlErrorSchema` method to our [AwsQueryCodecAPI](https://github.com/disneystreaming/smithy4s/blob/feature/aws-query-protocol/modules/aws/src/smithy4s/query/AwsQueryCodecAPI.scala#L132-L141), doing the same thing as "response" but with the `<ErrorResponse>` and `<Error>` tags (once again, see https://smithy.io/2.0/aws/protocols/aws-query-protocol.html#operation-error-serialization)

#### Fourth : 

Before the `Schema` into `XmlDocument.Decoder`, apply a transformation on the error `Schema` so that the unionSchema receives the `alloy#discriminated` trait with "Code" as a value, so that the `awsQueryError` of each alternative of the union schema receives `XmlName` containing whatever `Code` value the `AwsQueryError` instance contains.

**Comment by Baccata** [comment] 2023-07-24 13:48
Closing, this will be done in the scope of this issue : https://github.com/disneystreaming/smithy4s/issues/944

**Closed as completed by Baccata** 2023-07-24 13:48 UTC
