### ISSUE TITLE
Uninitialized field regression in 0.15.0

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#383] opened 2022-08-18 19:14 UTC
```scala
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.15.0")
```

```
namespace demo

@length(min: 1)
string MyString
```

```scala
object Main extends App {

  demo.MyString("test")
}
```

Result:

```
[error] Exception in thread "main" java.lang.ExceptionInInitializerError
[error]         at smithy.api.NonEmptyStringList$.<clinit>(NonEmptyStringList.scala:15)
[error]         at smithy.api.Trait$.<clinit>(Trait.scala:22)
[error]         at smithy.api.Documentation$.<clinit>(Documentation.scala:14)
[error]         at smithy.api.Length$.<clinit>(Length.scala:15)
[error]         at smithy4s.RefinementProvider$LengthConstraint.<init>(RefinementProvider.scala:86)
[error]         at smithy4s.RefinementProvider$.<clinit>(RefinementProvider.scala:72)
[error]         at demo.MyString$.<clinit>(MyString.scala:13)
[error]         at Main$.delayedEndpoint$Main$1(Main.scala:3)
[error]         at Main$delayedInit$body.apply(Main.scala:1)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:76)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at Main$.main(Main.scala:1)
[error]         at Main.main(Main.scala)
[error] Caused by: scala.UninitializedFieldError: Uninitialized field: /home/runner/work/smithy4s/smithy4s/modules/core/src/smithy4s/RefinementProvider.scala: 71
[error]         at smithy4s.RefinementProvider$.stringLengthConstraint(RefinementProvider.scala:71)
[error]         at smithy.api.NonEmptyString$.<clinit>(NonEmptyString.scala:15)
[error]         ... 21 more
```

This doesn't happen in 0.14.2. I believe it affects all newtypes with `@length`, possibly others.

Line in question: https://github.com/disneystreaming/smithy4s/blob/v0.15.0/modules/core/src/smithy4s/RefinementProvider.scala#L71

**Comment by kubukoz** [comment] 2022-08-18 19:15
Full repro at: https://github.com/kubukoz/demos/tree/smithy-newtype-uninitialized

**Comment by daddykotex** [comment] 2022-08-18 20:21
I've started looking into and I believe it's a circular dependency hidden in implicit resolution.
but in a gist:

The following `validated` needs an implicit constraint: `val underlyingSchema : Schema[String] = string.withId(id).addHints(hints).validated(smithy.api.Length(Some(1), None))`

It can be implicitly resolved by `stringLengthConstraint` from `RefinementProvider`

But to instantiate `Length`, we have to instantiate a few things:

1. Documentation
2. Trait
3. NonEmptyList
4. NonEmptyString

And NonEmptyString is defined in the same way as MyString, with a `length` annotation, so it also needs a `stringLengthConstraint` and thus starts the loop

**Comment by Baccata** [comment] 2022-08-18 20:31
Just turn the implicit RefinementProvider instances from val to def for string and bytearray, add regression tests. That will do

**Comment by kubukoz** [comment] 2022-08-18 21:55
AFAICS that doesn't help. The defs still have to get instantiated while you build `NonEmptyString`'s companion.

One thing that _seems_ to work is making `hints`, `underlyingSchema` and `schema` in `NES`'s companion lazy...

Also, I believe the tests aren't hitting this case because `Documentation` gets instantiated before `Length`. I can reproduce that change with a runnable snippet:

```scala
package smithy4s

import smithy.api.NonEmptyString

object demo {
  // comment this out for a surprise:
  smithy.api.Documentation
  // 
  def main(args: Array[String]) = println(NonEmptyString("test"))
}
```

**Comment by Baccata** [comment] 2022-08-18 22:13
indeed, you're right. 

I think it's just gonna be a case of computing the "isRecursive" predicate in the renderer a little bit differently and including the traits in the PathFinder that helps detecting recursion.

**Comment by Baccata** [comment] 2022-08-18 22:18
Or we could just go ahead and make lazy all schemas that are for shapes that are trait themselves (via `Schema.recursive` or similar)

**Comment by lewisjkl** [comment] 2022-08-18 22:55
The PR I linked there gives that second idea a try. Looks like that fixes it, but not sure if that is the ideal approach or not.

**Closed** 2022-08-19 03:38 UTC
Labels: bug
